logging:
 level:
   org.springframework.security: trace
   root: info
   com.team.logger: debug

hystrix:
 command:
   default:
     execution:
       isolation:
         thread:
           timeoutInMilliseconds: 20000

eureka:
 instance:
   preferIpAddress: true
 client:
   service-url:
     defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    loadbalancing:
      ribbon:
        enabled: false
