spring:
  jpa:
    open-in-view: true
    show-sql: true
    database: postgresql

    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://database:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  test:
    database:
      replace: none

  sql:
    init:
      platform: postgres


server:
  port: 8075

logging:
  level:
    com.team.authorizeservice: debug
    root: warn