spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        lower-case-service-id: true
      httpclient:
        ssl:
          useInsecureTrustManager: true

      routes:
        - id: users
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: products
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        - id: orders
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: identity
          uri: lb://identity-provider
          predicates:
            - Path=/api/auth/**

server:
  port: 8080