spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true

      routes:
        - id: users
          uri: http://user-service:8002
          predicates:
            - Path=/api/users/**

        - id: products
          uri: http://product-service:8001
          predicates:
            - Path=/api/products/**

        - id: orders
          uri: http://order-service:8003
          predicates:
            - Path=/api/orders/**

        - id: images
          uri: http://image-service:8005
          predicates:
            - Path=/api/images/**

server:
  port: 8080
