topic:
  name: t.activation.link

spring:
  kafka:
    bootstrap-servers: http://kafka:9092
    consumer:
      group-id: group-id
      auto-offset-reset: earliest

server:
  port: 8005

logging:
  level:
    com.team.notificationservice: debug
    root: warn