topic:
  name: t.activation.link

spring:
  kafka:
    consumer:
      group-id: "default"

server:
  port: 8005

logging:
  level:
    root: warn
    com.team.notificationservice: debug
    com.team.basejwt: debug
    com.team.jwtinit: debug
    com.team.jwtcommon: debug