spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

  datasource:
    url: jdbc:postgresql://product-database:5432/product_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  test:
    database:
      replace: none

  sql:
    init:
      platform: postgres

server:
  port: 8001

logging:
  level:
    root: warn
    com.team.productservice: debug
    com.team.basejwt: debug
    com.team.jwtinit: debug
    com.team.jwtcommon: debug