topic:
  name: t.activation.link

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

  datasource:
    url: jdbc:postgresql://user-database:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  test:
    database:
      replace: none

  sql:
    init:
      platform: postgres

server:
  port: 8002

logging:
  level:
    root: warn
    com.team.userservice: debug
    com.team.basejwt: debug
    com.team.jwtinit: debug
    com.team.jwtcommon: debug