topic:
  name: t.activation.link

spring:
  kafka:
    bootstrap-servers: http://kafka:9092
    producer:
      retries: 0
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

  datasource:
    url: jdbc:postgresql://user-database:5432/user_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  test:
    database:
      replace: none

  sql:
    init:
      platform: postgres

server:
  port: 8002

logging:
  level:
    com.team.userservice: debug
    root: warn

